if (Sys.getenv("CI") == "" ) {

  convert_arg <- function(arg) {
    if (is.call(arg)) stop("not supported yet, will deal with special cases later")
    arg
  }

  # TODO: this should live in the package somewhere
  udfs <- c(
    "==" = "r_base::==",
    "+"  = "r_base::+"
  )

  convert_call <- function(expr, type, ...) {
    fun <- as.character(rlang::node_car(expr))

    args <- as.list(expr[-1])
    args <- lapply(args, convert_arg)
    names(args) <- paste0("x", seq_along(args))

    list(
      fun = fun,
      udf = udfs[[fun]],
      data = tibble::as_tibble(args),
      expression = deparse(expr, nlines = 1L),
      type = type,
      ...
    )
  }

  convert_expr <- function(expr) {
    if (rlang::is_call(expr, "expect_udf_eq")){
      convert_call(
        rlang::node_cadr(expr),
        type = "udf_equal",
        expected = deparse(rlang::node_car(rlang::node_cddr(expr)))
      )
    } else if (rlang::is_call(expr, "expect_udf_na")) {
      convert_call(rlang::node_cadr(expr), type = "udf_na")
    } else {
      convert_call(expr, type = "udf_snapshot")
    }
  }

  gen_dir <- system.file(package = "duckdbrfuns", "tests", "testthat", "gen")
  gen_files <- list.files(gen_dir, pattern = "[.][rR]$")

  for (f in gen_files) {
    test_file_path <- system.file(package = "duckdbrfuns", "tests", "testthat", paste0("test-generated-", f))
    message(paste("\U2705 generating:", basename(test_file_path)))
    test_file <- file(test_file_path, open = "w")
    cat("# Generated by helper-gen.R: do not edit", "by hand\n", file = test_file)

    expressions <- parse(file.path(gen_dir, f))
    header <- sapply(expressions, is.character)
    group <- cumsum(header)

    description <- as.character(expressions[header])
    for (i in seq_along(description)) {
      desc <- description[[i]]

      exprs <- lapply(tail(expressions[group == i], -1), convert_expr)

      for (expr in exprs) {
        in_df <- paste(constructive::construct(expr$data)$code, collapse = "\n")
        args_references <- paste(glue::glue("             duckdb:::expr_reference('{names(expr$data)}')"), collapse = ", \n")
        expectation <- switch(expr$type,
          udf_equal    = glue::glue('expect_equal(out_df[, 1L], {expr$expected})'),
          udf_na       = glue::glue('expect_true(is.na(out_df[, 1L]))'),
          udf_snapshot = glue::glue('expect_snapshot(out_df)')
        )

        test_expr <- glue::glue(r"[
test_that('{desc} :: {expr$expression}', {{
    con <- local_con()
    in_df <- {in_df}
    in_rel <- duckdb:::rel_from_df(con, in_df)
    out_rel <- duckdb:::rel_project(
        in_rel,
        list(duckdb:::expr_function(
          '{expr$udf}',
          list(
{args_references}
          )
        ))
    )
    out_df <- duckdb:::rel_to_altrep(out_rel)

    {expectation}
}})


]")

        cat(test_expr, file = test_file)
      }
    }

    close(test_file)
  }

}
