# Generated by helper-gen.R: do not edit by hand
test_that(r"(<int> < <int> :: 0L < 0L)", {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0L, x2 = 0L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE)
})

test_that(r"(<int> < <int> :: 1L < 0L)", {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = 0L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE)
})

test_that(r"(<int> < <int> :: 1L < NA_integer_)", {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA)
})

test_that(r"(<int> < <int> :: NA_integer_ < 2L)", {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA)
})

test_that(r"(<int> < <int> :: NA_integer_ < NA_integer_)", {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA)
})

