# Generated by helper-gen.R: do not edit by hand
test_that('<int> == <int>', {
  con <- local_con()
  #  0L == 0L 
  in_df <- structure(list(x1 = 0L, x2 = 0L), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


  #  1L == 0L 
  in_df <- structure(list(x1 = 1L, x2 = 0L), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


  #  1L == NA_integer_ 
  in_df <- structure(list(x1 = 1L, x2 = NA_integer_), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


  #  NA_integer_ == 2L 
  in_df <- structure(list(x1 = NA_integer_, x2 = 2L), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


  #  NA_integer_ == NA_integer_ 
  in_df <- structure(list(x1 = NA_integer_, x2 = NA_integer_), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


})

test_that('<int> == <str>', {
  con <- local_con()
  #  NA_integer_ == "string" 
  in_df <- structure(list(x1 = NA_integer_, x2 = "string"), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


  #  1L == "1" 
  in_df <- structure(list(x1 = 1L, x2 = "1"), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -1L))
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(in_rel,
      list(duckdb:::expr_function(
        'r_base::==', 
        list(
          duckdb:::expr_reference('x1'),
          duckdb:::expr_reference('x2')
        )
      ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)
  expect_snapshot(out_df)


})

