# Generated by helper-gen.R: do not edit by hand
test_that('<dbl> + <dbl> :: 1 + 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 + 1)
})

test_that('<dbl> + <dbl> :: 1e+06 + 2e+06', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1e+06, x2 = 2e+06)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1e+06 + 2e+06)
})

test_that('<dbl> + <dbl> :: 1e+09 + 2e+09', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1e+09, x2 = 2e+09)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1e+09 + 2e+09)
})

test_that('<dbl> + <dbl> :: 1 + NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 + NA_real_)
})

test_that('<dbl> + <dbl> :: NA_real_ + 2', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = 2)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ + 2)
})

test_that('<int> + <int> :: 1L + 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L + 2L)
})

test_that('<int> + <int> :: NA_integer_ + 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ + 2L)
})

test_that('<int> + <int> :: 1L + NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L + NA_integer_)
})

test_that('<int> + <dbl> :: 1L + 3', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = 3)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L + 3)
})

test_that('<int> + <dbl> :: 3 + 1L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 3, x2 = 1L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 3 + 1L)
})

test_that('<int> + <dbl> :: 1L + NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L + NA_real_)
})

test_that('<int> + <dbl> :: NA_real_ + 1L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = 1L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ + 1L)
})

test_that('<int> + <dbl> :: NA_integer_ + 4', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = 4)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ + 4)
})

test_that('<int> + <dbl> :: 4 + NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 4, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 4 + NA_integer_)
})

test_that('<int> + <dbl> :: NA_integer_ + NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::+',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ + NA_real_)
})

