# Generated by helper-gen.R: do not edit by hand
test_that(r"(<str> <= <dbl> :: "2" <= 1)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2", x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "42.3" <= 42.3)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "42.3", x2 = 42.3)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "42.4" <= 42.3)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "42.4", x2 = 42.3)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "42.299999999" <= 42.3)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "42.299999999", x2 = 42.3)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "1" <= 1)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "1", x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "1" <= NA_real_)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "1", x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: NA_character_ <= 3)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = 3)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <dbl> :: "a" <= 1)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "a", x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<dbl> <= <str> :: 1 <= "2")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1, x2 = "2")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<dbl> <= <str> :: 1 <= "1")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1, x2 = "1")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<dbl> <= <str> :: NA_real_ <= "2")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = "2")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<dbl> <= <str> :: 3 <= NA_character_)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 3, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<dbl> <= <str> :: 1 <= "a")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1, x2 = "a")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<int> <= <str> :: NA_integer_ <= "string")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = "string")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<int> <= <str> :: 1L <= "1")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = "1")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<int> <= <str> :: 1L <= NA_character_)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<int> <= <str> :: 1L <= "a")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = "a")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <int> :: "string" <= NA_integer_)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "string", x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <int> :: "1" <= 1L)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "1", x2 = 1L)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <int> :: NA_character_ <= 2L)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<str> <= <int> :: "a" <= 1L)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "a", x2 = 1L)
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: time <= "2024-02-21 14:00:00")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"), x2 = "2024-02-21 14:00:00")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: time <= "2024-02-21 13:00:00")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"), x2 = "2024-02-21 13:00:00")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: time <= "2024-02-21 15:00:00")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"), x2 = "2024-02-21 15:00:00")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: "2024-02-21 14:00:00" <= time)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-21 14:00:00", x2 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: "2024-02-21 13:00:00" <= time)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-21 13:00:00", x2 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<time> <= <string> :: "2024-02-21 15:00:00" <= time)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-21 15:00:00", x2 = as.POSIXct("2024-02-21 14:00:00", tz = "UTC"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: date <= "2024-02-21")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.Date("2024-02-21"), x2 = "2024-02-21")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: date <= "2024-02-22")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.Date("2024-02-21"), x2 = "2024-02-22")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: date <= "2024-02-20")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.Date("2024-02-21"), x2 = "2024-02-20")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: date <= "2024-03-21 and then some")", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = as.Date("2024-02-21"), x2 = "2024-03-21 and then some")
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: "2024-02-21" <= date)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-21", x2 = as.Date("2024-02-21"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: "2024-02-22" <= date)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-22", x2 = as.Date("2024-02-21"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: "2024-02-20" <= date)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-02-20", x2 = as.Date("2024-02-21"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
test_that(r"(<date> <= <string> :: "2024-03-21 and then some" <= date)", {
  con <- local_duckdb_con()
  in_df <- tibble::tibble(x1 = "2024-03-21 and then some", x2 = as.Date("2024-02-21"))
  in_rel <- duckdb:::rel_from_df(con, in_df)

  expect_snapshot(error = TRUE, duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      "r_base::<=",
      list(
        duckdb:::expr_reference("x1"), 
        duckdb:::expr_reference("x2")
      )
    ))
  ))
})
