# Generated by helper-gen.R: do not edit by hand
test_that('<int> == <int> :: 0L == 0L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0L, x2 = 0L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 0L == 0L)
})

test_that('<int> == <int> :: 1L == 0L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = 0L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L == 0L)
})

test_that('<int> == <int> :: 1L == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L == NA_integer_)
})

test_that('<int> == <int> :: NA_integer_ == 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == 2L)
})

test_that('<int> == <int> :: NA_integer_ == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == NA_integer_)
})

test_that('<lgl> == <lgl> :: TRUE == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == TRUE)
})

test_that('<lgl> == <lgl> :: TRUE == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == FALSE)
})

test_that('<lgl> == <lgl> :: FALSE == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == TRUE)
})

test_that('<lgl> == <lgl> :: FALSE == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == FALSE)
})

test_that('<lgl> == <lgl> :: NA == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == FALSE)
})

test_that('<lgl> == <lgl> :: NA == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == TRUE)
})

test_that('<lgl> == <lgl> :: TRUE == NA', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = NA)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == NA)
})

test_that('<lgl> == <lgl> :: FALSE == NA', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = NA)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == NA)
})

test_that('<int> == <lgl> :: 1 == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == TRUE)
})

test_that('<int> == <lgl> :: 1 == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == FALSE)
})

test_that('<int> == <lgl> :: 2 == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2 == TRUE)
})

test_that('<int> == <lgl> :: 2 == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2 == FALSE)
})

test_that('<int> == <lgl> :: 0 == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 0 == TRUE)
})

test_that('<int> == <lgl> :: 0 == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 0 == FALSE)
})

test_that('<int> == <lgl> :: NA_integer_ == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == TRUE)
})

test_that('<int> == <lgl> :: NA_integer_ == NA', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = NA)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == NA)
})

test_that('<int> == <lgl> :: 42 == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 42, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 42 == NA_integer_)
})

test_that('<lgl> == <int> :: TRUE == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == 1)
})

test_that('<lgl> == <int> :: FALSE == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == 1)
})

test_that('<lgl> == <int> :: TRUE == 2', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = 2)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == 2)
})

test_that('<lgl> == <int> :: FALSE == 2', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = 2)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == 2)
})

test_that('<lgl> == <int> :: TRUE == 0', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = 0)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == 0)
})

test_that('<lgl> == <int> :: FALSE == 0', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = 0)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == 0)
})

test_that('<lgl> == <int> :: TRUE == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == NA_integer_)
})

test_that('<lgl> == <int> :: NA == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == NA_integer_)
})

test_that('<lgl> == <int> :: NA == 42', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = 42)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == 42)
})

test_that('<dbl> == <dbl> :: 1.5 == 2', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1.5, x2 = 2)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1.5 == 2)
})

test_that('<dbl> == <dbl> :: 1.5 == 1.5', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1.5, x2 = 1.5)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1.5 == 1.5)
})

test_that('<dbl> == <dbl> :: 1.5 == NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1.5, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1.5 == NA_real_)
})

test_that('<dbl> == <dbl> :: NA_real_ == 2.5', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = 2.5)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ == 2.5)
})

test_that('<dbl> == <int | lgl> :: 2 == 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2 == 2L)
})

test_that('<dbl> == <int | lgl> :: 3.5 == 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 3.5, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 3.5 == 2L)
})

test_that('<dbl> == <int | lgl> :: 3.5 == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 3.5, x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 3.5 == NA_integer_)
})

test_that('<dbl> == <int | lgl> :: 1 == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == TRUE)
})

test_that('<dbl> == <int | lgl> :: 1 == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == FALSE)
})

test_that('<dbl> == <int | lgl> :: 0 == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 0 == FALSE)
})

test_that('<dbl> == <int | lgl> :: 0 == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 0, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 0 == TRUE)
})

test_that('<dbl> == <int | lgl> :: 2 == NA', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2, x2 = NA)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2 == NA)
})

test_that('<dbl> == <int | lgl> :: NA_real_ == 42L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = 42L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ == 42L)
})

test_that('<dbl> == <int | lgl> :: NA_real_ == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ == TRUE)
})

test_that('<dbl> == <int | lgl> :: NA_real_ == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ == FALSE)
})

test_that('<int | lgl> == <dbl> :: 2L == 2', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2L, x2 = 2)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2L == 2)
})

test_that('<int | lgl> == <dbl> :: 2L == 3.5', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 2L, x2 = 3.5)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 2L == 3.5)
})

test_that('<int | lgl> == <dbl> :: NA_integer_ == 3.5', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = 3.5)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == 3.5)
})

test_that('<int | lgl> == <dbl> :: TRUE == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == 1)
})

test_that('<int | lgl> == <dbl> :: FALSE == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == 1)
})

test_that('<int | lgl> == <dbl> :: FALSE == 0', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = 0)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == 0)
})

test_that('<int | lgl> == <dbl> :: TRUE == 0', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = 0)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == 0)
})

test_that('<int | lgl> == <dbl> :: NA == 0', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = 0)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == 0)
})

test_that('<int | lgl> == <dbl> :: 42L == NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 42L, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 42L == NA_real_)
})

test_that('<int | lgl> == <dbl> :: TRUE == NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == NA_real_)
})

test_that('<int | lgl> == <dbl> :: FALSE == NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == NA_real_)
})

test_that('<str> == <str> :: "a" == "b"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "a", x2 = "b")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "a" == "b")
})

test_that('<str> == <str> :: "a" == "a"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "a", x2 = "a")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "a" == "a")
})

test_that('<str> == <str> :: "a" == NA_character_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "a", x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "a" == NA_character_)
})

test_that('<str> == <str> :: NA_character_ == "a"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = "a")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_character_ == "a")
})

test_that('<str>        == <lgl> :: "TRUE" == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "TRUE", x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "TRUE" == TRUE)
})

test_that('<str>        == <lgl> :: "TRUE" == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "TRUE", x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "TRUE" == FALSE)
})

test_that('<str>        == <lgl> :: "TRUE" == NA', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "TRUE", x2 = NA)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "TRUE" == NA)
})

test_that('<str>        == <lgl> :: NA_character_ == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_character_ == TRUE)
})

test_that('<str>        == <lgl> :: NA_character_ == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_character_ == FALSE)
})

test_that('<str>        == <lgl> :: "FALSE" == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "FALSE", x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "FALSE" == TRUE)
})

test_that('<str>        == <lgl> :: "FALSE" == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "FALSE", x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "FALSE" == FALSE)
})

test_that('<str>        == <lgl> :: "tRue" == TRUE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "tRue", x2 = TRUE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "tRue" == TRUE)
})

test_that('<str>        == <lgl> :: "fAlse" == FALSE', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "fAlse", x2 = FALSE)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "fAlse" == FALSE)
})

test_that('<lgl> == <str> :: TRUE == "TRUE"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = "TRUE")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == "TRUE")
})

test_that('<lgl> == <str> :: FALSE == "TRUE"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = "TRUE")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == "TRUE")
})

test_that('<lgl> == <str> :: NA == "TRUE"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA, x2 = "TRUE")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA == "TRUE")
})

test_that('<lgl> == <str> :: TRUE == NA_character_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == NA_character_)
})

test_that('<lgl> == <str> :: FALSE == NA_character_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == NA_character_)
})

test_that('<lgl> == <str> :: TRUE == "FALSE"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = "FALSE")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == "FALSE")
})

test_that('<lgl> == <str> :: FALSE == "FALSE"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = "FALSE")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == "FALSE")
})

test_that('<lgl> == <str> :: TRUE == "tRue"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = TRUE, x2 = "tRue")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], TRUE == "tRue")
})

test_that('<lgl> == <str> :: FALSE == "fAlse"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = FALSE, x2 = "fAlse")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], FALSE == "fAlse")
})

test_that('<str> == <dbl> :: "2" == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "2", x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "2" == 1)
})

test_that('<str> == <dbl> :: "1" == 1', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "1", x2 = 1)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "1" == 1)
})

test_that('<str> == <dbl> :: "1" == NA_real_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "1", x2 = NA_real_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "1" == NA_real_)
})

test_that('<str> == <dbl> :: NA_character_ == 3', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = 3)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_character_ == 3)
})

test_that('<dbl> == <str> :: 1 == "2"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = "2")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == "2")
})

test_that('<dbl> == <str> :: 1 == "1"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1, x2 = "1")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1 == "1")
})

test_that('<dbl> == <str> :: NA_real_ == "2"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_real_, x2 = "2")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_real_ == "2")
})

test_that('<dbl> == <str> :: 3 == NA_character_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 3, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 3 == NA_character_)
})

test_that('<int> == <str> :: NA_integer_ == "string"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_integer_, x2 = "string")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_integer_ == "string")
})

test_that('<int> == <str> :: 1L == "1"', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = "1")
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L == "1")
})

test_that('<int> == <str> :: 1L == NA_character_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = 1L, x2 = NA_character_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], 1L == NA_character_)
})

test_that('<str> == <int> :: "string" == NA_integer_', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "string", x2 = NA_integer_)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "string" == NA_integer_)
})

test_that('<str> == <int> :: "1" == 1L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = "1", x2 = 1L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], "1" == 1L)
})

test_that('<str> == <int> :: NA_character_ == 2L', {
  con <- local_con()
  in_df <- tibble::tibble(x1 = NA_character_, x2 = 2L)
  in_rel <- duckdb:::rel_from_df(con, in_df)
  out_rel <- duckdb:::rel_project(
    in_rel,
    list(duckdb:::expr_function(
      'r_base::==',
      list(
        duckdb:::expr_reference('x1'), 
        duckdb:::expr_reference('x2')
      )
    ))
  )
  out_df <- duckdb:::rel_to_altrep(out_rel)

  expect_identical(out_df[, 1], NA_character_ == 2L)
})

