#
# This workflow runs (some of) the client test for the DuckDB extension. These should only be used when necessary, writing
# regular SQL tests is generally preferable. Feel free to remove this workflow for your extension.
#

name: Client specific tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "20 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  client-tests:
    name: Client Tests
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_client_tests.yml@v1.1.0
    with:
      duckdb_version: v1.1.0
