# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      GEN: ninja
    steps:
      - name: Install Ninja
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq ninja-build

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
        
      - name: Checkout DuckDB to version
        run: |
          cd duckdb
          git checkout v0.9.2
      
      - name: build duckdb extension
        run: make

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: duckdb-rfuns-r
          
      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: duckdb-rfuns-r

